using System.Text.Json;
using System.Text.Json.Serialization;

namespace VoiceTranscript.Core.Storage;

/// <summary>
/// Who this archive is.
///
/// The user runs this application on more than one computer and carries conversations between
/// them by hand. Until now neither copy had a name, so neither could say anything true about the
/// other: an import was an anonymous file arriving from nowhere, and "en son ne zaman haber
/// aldım" had no answer because there was nothing to be the subject of the sentence.
///
/// The id is generated by the machine and never edited — it is what two archives recognise each
/// other by across renames. <paramref name="Label"/> is the only part the user writes, and NULL
/// means they have not named this computer yet, not that it has no name.
/// </summary>
public sealed record ArchiveIdentity(string Id, string? Label, DateTimeOffset CreatedAt)
{
    /// <summary>The label if there is one, otherwise a short form of the id — never blank.</summary>
    public string Display => string.IsNullOrWhiteSpace(Label) ? Id[..Math.Min(8, Id.Length)] : Label!;
}

/// <summary>
/// Another archive this one has met, and when.
///
/// <paramref name="WrittenAt"/> is when the backup was written over there. NULL means the file
/// carried no manifest and this machine does not know — which is a different thing from a date
/// long ago, and the screen must not turn one into the other.
///
/// <paramref name="ImportedAt"/> is never null: it is the instant the merge ran here.
/// </summary>
public sealed record ArchiveLink(
    string ArchiveId,
    string? Label,
    DateTimeOffset? WrittenAt,
    DateTimeOffset ImportedAt)
{
    public string Display => string.IsNullOrWhiteSpace(Label)
        ? ArchiveId[..Math.Min(8, ArchiveId.Length)]
        : Label!;
}

/// <summary>
/// What a backup file says about itself, before anything is unpacked.
///
/// Written into the archive as <c>manifest.json</c> so that an import can be previewed rather
/// than discovered: who wrote it, when, how much is in it, WHETHER THE AUDIO IS THERE, and what
/// schema it speaks. The audio question is the one that used to be answered only by importing
/// and then noticing that nothing can be played — the default backup button does not include it,
/// and nobody was told.
///
/// A backup written before this existed has no manifest at all. That reads as UNKNOWN and must
/// never read as corrupt: those files import perfectly well, and refusing one — or even calling
/// it damaged on screen — would be this application lying about its own older self.
/// </summary>
public sealed record BackupManifest(
    string ArchiveId,
    string? Label,
    DateTimeOffset WrittenAt,
    int Calls,
    int Contacts,
    bool IncludesAudio,
    int SchemaVersion,
    string? AppVersion)
{
    /// <summary>The entry name inside the zip. At the root, beside data/ and recordings/.</summary>
    public const string EntryName = "manifest.json";

    public string Display => string.IsNullOrWhiteSpace(Label)
        ? ArchiveId[..Math.Min(8, ArchiveId.Length)]
        : Label!;

    /// <summary>
    /// Whether the file was written by a build that knows more than this one does.
    ///
    /// Not a refusal and not an error. The merge intersects the columns of both databases, so an
    /// unknown column is left behind — which is the right behaviour and the wrong thing to keep
    /// quiet about, hence this being on the manifest where a screen can read it.
    /// </summary>
    public bool FromANewerBuild => SchemaVersion > Schema.Version;

    private static readonly JsonSerializerOptions Json = new()
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.Never,
    };

    public string ToJson() => JsonSerializer.Serialize(this, Json);

    /// <summary>
    /// Reads a manifest, or returns null.
    ///
    /// Null for every failure without distinction — absent, truncated, written by something else,
    /// holding a shape this build cannot parse — because the caller's answer is the same in all
    /// of those cases and it is "kaynak bilinmiyor". A manifest is a courtesy the file pays to
    /// the screen; nothing about the import depends on it, so nothing about the import may fail
    /// because of it.
    /// </summary>
    public static BackupManifest? FromJson(string? json)
    {
        if (string.IsNullOrWhiteSpace(json)) return null;

        try
        {
            var read = JsonSerializer.Deserialize<BackupManifest>(json, Json);

            // An id is the one field the rest is meaningless without: it is what a link row is
            // keyed by, so a manifest without one cannot say who wrote the file.
            return string.IsNullOrWhiteSpace(read?.ArchiveId) ? null : read;
        }
        catch (JsonException)
        {
            return null;
        }
    }
}
